/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/v1/decision": {
    /** Evaluate a policy decision (PDP) */
    post: operations["postDecision"];
  };
  "/v1/tools": {
    /** List tools (tenant-scoped) */
    get: operations["listTools"];
    /** Create tool (tenant-scoped) */
    post: operations["createTool"];
  };
  "/v1/policies": {
    /** List policies (tenant-scoped) */
    get: operations["listPolicies"];
    /** Create policy (tenant-scoped) */
    post: operations["createPolicy"];
  };
  "/v1/policies/activate": {
    /** Activate a policy by ID (tenant-scoped) */
    post: operations["activatePolicy"];
  };
  "/v1/policies/active": {
    /** Get active policy (tenant-scoped) */
    get: operations["getActivePolicy"];
  };
  "/v1/policies/simulate": {
    /** Simulate a decision against active policy (or supplied policy JSON) */
    post: operations["simulatePolicy"];
  };
  "/v1/receipts": {
    /** List recent receipts (decision + invocation) */
    get: operations["listReceipts"];
    /** Ingest a receipt (tenant-scoped) */
    post: operations["createReceipt"];
  };
  "/v1/receipts/verify": {
    /** Verify receipt hash chain */
    post: operations["verifyReceipts"];
  };
  "/v1/receipts/export": {
    /** Export receipts (JSON or CSV) */
    get: operations["exportReceipts"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ErrorResponse: {
      error: {
        /** @description Stable error identifier. */
        code: string;
        message: string;
        /** @description Optional field-level validation issues. */
        details?: {
            field?: string;
            message?: string;
          }[];
      };
      request_id: string;
      decision_id?: string;
      trace_id?: string;
    };
    TenantContext: {
      tenant_id: string;
    };
    Actor: {
      type: string;
      id: string;
      roles?: string[];
      source?: string;
    };
    ToolContext: {
      name: string;
      method: string;
      endpoint: string;
    };
    MCPContext: {
      server: string;
      tool: string;
      method: string;
      workspace?: string;
    };
    TraceContext: {
      request_id?: string;
      trace_id?: string;
      span_id?: string;
    };
    DecisionRequest: {
      tenant: components["schemas"]["TenantContext"];
      actor: components["schemas"]["Actor"];
      tool: components["schemas"]["ToolContext"];
      mcp?: components["schemas"]["MCPContext"];
      trace?: components["schemas"]["TraceContext"];
    };
    Obligation: {
      kind: string;
      params?: {
        [key: string]: string;
      };
    };
    DecisionResponse: {
      /** @enum {string} */
      decision: "allow" | "deny";
      decision_id: string;
      policy_version?: number;
      policy_hash?: string;
      rule_index?: number | null;
      obligations?: components["schemas"]["Obligation"][];
      reason?: string;
      request_id?: string;
      trace_id?: string;
      span_id?: string;
    };
    Tool: {
      id: string;
      name: string;
      kind: string;
      config?: {
        [key: string]: unknown;
      };
    };
    ToolList: {
      items?: components["schemas"]["Tool"][];
    };
    CreateToolRequest: {
      name: string;
      kind: string;
      config?: {
        [key: string]: unknown;
      };
    };
    Policy: {
      id: string;
      name: string;
      version: number;
      active: boolean;
      policy_hash: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** @description JSON policy document */
      policy?: {
        [key: string]: unknown;
      };
    };
    PolicyList: {
      items?: components["schemas"]["Policy"][];
    };
    CreatePolicyRequest: {
      name: string;
      policy: {
        [key: string]: unknown;
      };
    };
    SimulateRequest: {
      actor_roles?: string[];
      method: string;
      path: string;
      /** @description Optional policy JSON to simulate against instead of active policy */
      policy?: {
        [key: string]: unknown;
      };
    };
    SimulateResponse: {
      /** @enum {string} */
      decision: "allow" | "deny";
      reason: string;
      rule_index?: number | null;
      policy_hash?: string;
      policy_version?: number;
    };
    ActivePolicyResponse: {
      id: string;
      name: string;
      version: number;
      policy_hash: string;
      /** Format: date-time */
      updated_at: string;
    };
    ReceiptList: {
      items?: {
          [key: string]: unknown;
        }[];
      /** Format: date-time */
      next_before?: string;
    };
    ReceiptExportResponse: {
      schema_version: string;
      items: components["schemas"]["ReceiptExportRecord"][];
    };
    ReceiptExportRecord: {
      schema_version: string;
      /** @enum {string} */
      kind: "decision" | "invocation";
      /** Format: date-time */
      ts: string;
      request_id?: string;
      decision_id?: string;
      trace_id?: string;
      policy_hash?: string;
      policy_version?: number;
      /** @enum {string} */
      decision?: "allow" | "deny";
      actor_id?: string;
      tool_name?: string;
      method?: string;
      path?: string;
      outcome?: string;
      status_code?: number;
      /**
       * @example RSASSA_PSS_SHA_256
       * @enum {string}
       */
      signature_alg?: "RSASSA_PSS_SHA_256" | "ECDSA_P256_SHA256";
      /** @example key://placeholder */
      signature_kid?: string;
      /** @example MEQCIE2v6y0h1t4z1Yq8w5x7h4c9S+u4k0mCwXr1o7sJ2aQ0AiA8Z0p2m3t4s5u6v7w8x9y0zA1b2c3d4e5f6g7h8i9j0k= */
      signature?: string;
      /**
       * Format: date-time
       * @example 2025-01-01T00:00:00Z
       */
      signed_at?: string;
      receipt_hash: string;
      receipt_prev_hash?: string;
    };
    ReceiptIngestRequest: components["schemas"]["DecisionReceiptIngest"] | components["schemas"]["InvocationReceiptIngest"];
    ReceiptIngestResponse: {
      receipt_id: string;
      hash: string;
      prev_hash?: string;
    };
    ReceiptVerifyFailure: {
      receipt_id: string;
      code: string;
    };
    ReceiptVerifyResponse: {
      ok: boolean;
      checked: number;
      /** @enum {string} */
      kind: "decision" | "invocation" | "all";
      failure?: components["schemas"]["ReceiptVerifyFailure"];
    };
    ReceiptIngestBase: {
      /** @enum {string} */
      kind: "decision" | "invocation";
      /** @description Idempotency key for receipt ingest (tenant-scoped). */
      request_id: string;
      decision_id?: string;
      trace_id?: string;
      span_id?: string;
      /**
       * @example RSASSA_PSS_SHA_256
       * @enum {string}
       */
      signature_alg?: "RSASSA_PSS_SHA_256" | "ECDSA_P256_SHA256";
      /** @example key://placeholder */
      signature_kid?: string;
      /** @example MEQCIE2v6y0h1t4z1Yq8w5x7h4c9S+u4k0mCwXr1o7sJ2aQ0AiA8Z0p2m3t4s5u6v7w8x9y0zA1b2c3d4e5f6g7h8i9j0k= */
      signature?: string;
      /**
       * Format: date-time
       * @example 2025-01-01T00:00:00Z
       */
      signed_at?: string;
      /** @description Redacted receipt payload (no raw tool args by default). */
      body: {
        [key: string]: unknown;
      };
    };
    DecisionReceiptIngest: components["schemas"]["ReceiptIngestBase"] & ({
      /** @enum {string} */
      decision: "allow" | "deny";
      policy_hash: string;
      policy_version?: number;
    });
    InvocationReceiptIngest: components["schemas"]["ReceiptIngestBase"] & ({
      tool_name: string;
      method: string;
      path: string;
      /** @enum {string} */
      outcome: "success" | "error" | "denied";
      status_code?: number;
      latency_ms: number;
      policy_hash?: string;
      policy_version?: number;
    });
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: {
    /** @description Correlation ID for the request (also present in response body when applicable). */
    RequestId: string;
  };
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Evaluate a policy decision (PDP) */
  postDecision: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["DecisionRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["DecisionResponse"];
        };
      };
      /** @description Invalid request */
      400: {
        headers: {
          "x-umbra-request-id": components["headers"]["RequestId"];
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Policy evaluation error */
      500: {
        headers: {
          "x-umbra-request-id": components["headers"]["RequestId"];
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description PDP unavailable */
      503: {
        headers: {
          "x-umbra-request-id": components["headers"]["RequestId"];
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** List tools (tenant-scoped) */
  listTools: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ToolList"];
        };
      };
      /** @description Invalid request */
      400: {
        headers: {
          "x-umbra-request-id": components["headers"]["RequestId"];
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Storage error */
      500: {
        headers: {
          "x-umbra-request-id": components["headers"]["RequestId"];
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Create tool (tenant-scoped) */
  createTool: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateToolRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["Tool"];
        };
      };
      /** @description Invalid request */
      400: {
        headers: {
          "x-umbra-request-id": components["headers"]["RequestId"];
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Storage error */
      500: {
        headers: {
          "x-umbra-request-id": components["headers"]["RequestId"];
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** List policies (tenant-scoped) */
  listPolicies: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["PolicyList"];
        };
      };
      /** @description Invalid request */
      400: {
        headers: {
          "x-umbra-request-id": components["headers"]["RequestId"];
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Storage error */
      500: {
        headers: {
          "x-umbra-request-id": components["headers"]["RequestId"];
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Create policy (tenant-scoped) */
  createPolicy: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePolicyRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["Policy"];
        };
      };
      /** @description Invalid request */
      400: {
        headers: {
          "x-umbra-request-id": components["headers"]["RequestId"];
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Storage error */
      500: {
        headers: {
          "x-umbra-request-id": components["headers"]["RequestId"];
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Activate a policy by ID (tenant-scoped) */
  activatePolicy: {
    requestBody: {
      content: {
        "application/json": {
          policy_id: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": {
            ok?: boolean;
          };
        };
      };
      /** @description Invalid request */
      400: {
        headers: {
          "x-umbra-request-id": components["headers"]["RequestId"];
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          "x-umbra-request-id": components["headers"]["RequestId"];
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Storage error */
      500: {
        headers: {
          "x-umbra-request-id": components["headers"]["RequestId"];
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Get active policy (tenant-scoped) */
  getActivePolicy: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ActivePolicyResponse"];
        };
      };
      /** @description No active policy */
      404: {
        headers: {
          "x-umbra-request-id": components["headers"]["RequestId"];
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Storage unavailable */
      503: {
        headers: {
          "x-umbra-request-id": components["headers"]["RequestId"];
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Simulate a decision against active policy (or supplied policy JSON) */
  simulatePolicy: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SimulateRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SimulateResponse"];
        };
      };
      /** @description Invalid request */
      400: {
        headers: {
          "x-umbra-request-id": components["headers"]["RequestId"];
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Storage error */
      500: {
        headers: {
          "x-umbra-request-id": components["headers"]["RequestId"];
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** List recent receipts (decision + invocation) */
  listReceipts: {
    parameters: {
      query?: {
        limit?: number;
        kind?: "decision" | "invocation";
        /** @description Best-effort substring search across receipt JSON (V0) */
        q?: string;
        /** @description Cursor for pagination (RFC3339 timestamp, exclusive) */
        before?: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ReceiptList"];
        };
      };
      /** @description Invalid request */
      400: {
        headers: {
          "x-umbra-request-id": components["headers"]["RequestId"];
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Storage error */
      500: {
        headers: {
          "x-umbra-request-id": components["headers"]["RequestId"];
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Ingest a receipt (tenant-scoped) */
  createReceipt: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReceiptIngestRequest"];
      };
    };
    responses: {
      /** @description Idempotent replay (existing receipt) */
      200: {
        content: {
          "application/json": components["schemas"]["ReceiptIngestResponse"];
        };
      };
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["ReceiptIngestResponse"];
        };
      };
      /** @description Invalid request */
      400: {
        headers: {
          "x-umbra-request-id": components["headers"]["RequestId"];
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Request ID conflict */
      409: {
        headers: {
          "x-umbra-request-id": components["headers"]["RequestId"];
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Storage error */
      500: {
        headers: {
          "x-umbra-request-id": components["headers"]["RequestId"];
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Verify receipt hash chain */
  verifyReceipts: {
    parameters: {
      query?: {
        kind?: "decision" | "invocation" | "all";
        limit?: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ReceiptVerifyResponse"];
        };
      };
      /** @description Invalid request */
      400: {
        headers: {
          "x-umbra-request-id": components["headers"]["RequestId"];
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Storage error */
      500: {
        headers: {
          "x-umbra-request-id": components["headers"]["RequestId"];
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /** Export receipts (JSON or CSV) */
  exportReceipts: {
    parameters: {
      query?: {
        format?: "json" | "csv";
        from?: string;
        to?: string;
        actor_id?: string;
        tool?: string;
        decision?: "allow" | "deny";
        request_id?: string;
        decision_id?: string;
        limit?: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ReceiptExportResponse"];
          "text/csv": string;
        };
      };
      /** @description Invalid request */
      400: {
        headers: {
          "x-umbra-request-id": components["headers"]["RequestId"];
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Storage error */
      500: {
        headers: {
          "x-umbra-request-id": components["headers"]["RequestId"];
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
